on: [push]
name: Build
jobs:
  build:
    strategy:
      matrix:
        # This is just a version to compile the integration_test.go; see
        # golangVersions in that file for the list of actual Go versions used.
        go-version: [1.x]
        os: [ubuntu-latest] # TODO: Add [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get -y install autoconf automake libtool curl make g++ unzip
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3.0.2
      with:
        path: .cache
        key: ${{ runner.os }}-${{ hashFiles('integration_test.go') }}
    - name: Build
      run: USE_BAZEL_VERSION=6.1.0 ./release.bash
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: bin
